import { Route, Routes } from 'react-router-dom'
import { SiteLayout } from '../components/layout/SiteLayout'
import { CompaniesPage } from '../pages/CompaniesPage'
import { AboutPage } from '../pages/AboutPage'
import { BlogPage } from '../pages/BlogPage'
import { ContactPage } from '../pages/ContactPage'
import { CourseDetailPage } from '../pages/CourseDetailPage'
import { CoursesPage } from '../pages/CoursesPage'
import { HomePage } from '../pages/HomePage'
import { MethodPage } from '../pages/MethodPage'
import { NotFoundPage } from '../pages/NotFoundPage'
export function AppRouter() { return <Routes><Route element={<SiteLayout/>}><Route index element={<HomePage/>}/><Route path="nosotros" element={<AboutPage/>}/><Route path="cursos" element={<CoursesPage/>}/><Route path="cursos/:courseSlug" element={<CourseDetailPage/>}/><Route path="metodo" element={<MethodPage/>}/><Route path="empresas" element={<CompaniesPage/>}/><Route path="blog" element={<BlogPage/>}/><Route path="contacto" element={<ContactPage/>}/><Route path="*" element={<NotFoundPage/>}/></Route></Routes> }
